### ISSUE TITLE
Can it run on windows

### ISSUE THREAD

**Issue by lgufan** [pinpoint-apm/pinpoint-go-agent#4]
能否让它在windows运行

**Comment by Endling-1077** [comment]
the same question,I can't run on windows

**Comment by lgufan** [comment]
> the same question,I can't run on windows
因为使用了专属linux的api，所以不能运行

**Comment by lgufan** [comment]
> the same question,I can't run on windows

是因为使用了linux的专属api，倒是无法运行的
