### ISSUE TITLE
How to avoid data race when send message with sarama plugin?

### ISSUE THREAD

**Issue by hwwwi** [pinpoint-apm/pinpoint-go-agent#78]
# Description
I have a wrapper function of sendMessage to produce messages with a tracer. (attached below)
Since the `ppsarama.WithContext(ctx, producer)` access the ctx inside of producer, the data race will occur when I run this function with multiple goroutines. 
It would be lovely if I can pass the context to `SendMessage` function, but it seems syncProducer interface doesn't support the context.
I can make a lock with mutex before the `WithContext`, but is there a way to prevent this without a lock? 

```golang
func sendMessageWrapper() {
	tracer := pinpoint.GetAgent().NewSpanTracer("Sarama Producer Invocation", fmt.Sprintf("kafka://topic=%s", topic))
	defer func() {
		tracer.EndSpan()
	}()
	
	ctx = pinpoint.NewContext(ctx, tracer)
	ppsarama.WithContext(ctx, producer) // <--- data race !
	_, _, err := producer.SendMessage(&sarama.ProducerMessage{
		Topic:   topic,
		Key:     sarama.StringEncoder(key),
		Value:   sarama.ByteEncoder(message),
		Headers: kafkaRecordHeaders,
	})
}
```

**Comment by dwkang** [comment]
In order to minimize modification of the application, the syncProducer interface of plugin was made to be the same as sarama's api. I think I need to add a new api to solve the problem.

I will provide a new SendMessageWithContext(ctx context.Context, ...) function.
