### ISSUE TITLE
Ownership of sarama is now IBM

### ISSUE THREAD

**Issue by smallfish06** [pinpoint-apm/pinpoint-go-agent#82]
Ownership of sarama has changed to IBM. 

https://github.com/IBM/sarama/releases/tag/v1.41.0

It can be breaking change cause pinpoint use v1.26.4. 
Will it be ok to change `github.com/Shopify/sarama` to `github.com/IBM/sarama`?

> interface doesn't changed that much and seems like ok

**Comment by dwkang** [comment]
I just changed the module name in the existing code and it doesn't build. I think it would be better to add a new package module that supports IBM/sarama to avoid breaking anything.

**Comment by smallfish06** [comment]
I tried to make test fail or build fail, but it always successfully built. How can I test whether build fails or not?

I built like below
```go
replace github.com/pinpoint-apm/pinpoint-go-agent/plugin/sarama-IBM v1.3.0-patch => github.com/smallfish06/pinpoint-go-agent/plugin/sarama-IBM v0.0.0-20231006061702-cbce9125120f

```
