### ISSUE TITLE
About updating go directive

### ISSUE THREAD

**Issue by smallfish06** [pinpoint-apm/pinpoint-go-agent#89]
Some of imported module in plugins are using go > 1.15

example:
- https://github.com/redis/go-redis/blob/v9.0.2/go.mod
- https://github.com/redis/go-redis/blob/v8.11.5/go.mod
- https://github.com/IBM/sarama/blob/v1.40.0/go.mod
- https://github.com/jackc/pgx/blob/v5.0.0/go.mod
- https://github.com/labstack/echo/blob/v4.9.0/go.mod

and more of it.

Also some releases are now moving >= 1.19
- https://github.com/IBM/sarama/releases/tag/v1.43.0
- https://github.com/redis/go-redis?tab=readme-ov-file#installation (supports 2 last Go versions)
- https://github.com/labstack/echo?tab=readme-ov-file#installation (supports 4 last Go versions)

It can be big concern while it is being imported by several other services. 

Are there any plan of updating go directive of pinpoint-go-agent?

**Comment by minwoo-jung** [comment]
@dwkang please review issue.

**Comment by dwkang** [comment]
I'm sorry for the delay in checking the issue.
I will update the go direct version to 1.20 or higher and release it soon.

**Comment by dwkang** [comment]
It is scheduled to be released on June 17.
