### ISSUE TITLE
ppgrpc happens panic

### ISSUE THREAD

**Issue by johnny-luojj** [pinpoint-apm/pinpoint-go-agent#92]
Hi, I encountered the following error while using ppgrpc. Could anyone provide help. 
My agent version is V1.3.0 . 
If any more infomation is needed, please let me know.
  
<img width="812" alt="企业微信截图_17235979613667" src="https://github.com/user-attachments/assets/3f1a98e0-bb53-4a05-8a4d-b4bbbba39353">

**Comment by dwkang** [comment]
This problem has been fixed in version v1.3.3.
https://github.com/pinpoint-apm/pinpoint-go-agent/releases/tag/v1.3.3

Use v1.3.3 or later releases.
